#!/bin/bash
if [ "$(id -u)" != 0 ]; then
kdialog --title "Permission Denied! " --error "This OS optimization script need root privileges to run. "
[ ! -d '/Applications/SGOffice.app' ] && kdialog --title "Error! " --error "Sogwang Office is required to display the root tutorial! Ignore this if you already know what to do. "
rootsetting
'/Applications/SGOffice.app/Contents/RedStar/soffice' '/media/RedStarOS_3.5/RootTutorial.rtf'
fi
if [ "$(id -u)" == 0 ]; then
kdialog --title "Root permission grant success! " --error "OS Optimization Process Will Now Begin. "
cp '/media/RedStarOS_3.5/RedStar/optimize.sh' '/root/Desktop/Redstar Optimize.sh' -fd
chmod +x '/root/Desktop/Redstar Optimize.sh'
konsole -e bash -c '/root/Desktop/Redstar\ Optimize.sh'
rm -f '/root/Desktop/Redstar Optimize.sh'
kdialog --title "Basic Optimization Completed! " --error "We've just completed some basic optimizations to RedStar OS 3.0 and it's now ready to be used by a foreigner outside DPRK. \nYou can install the v3.5 Update Combo on your desktop for even further optimizations. \nBesides, we've also prepared an old VMware Tools installer that is compatible with RedStar OS on your desktop that you can use to get a better experience in a VM. \n\nHave fun playing around!     : )\nMade By: happy_mimimix"
fi