#!/bin/bash
if [ "$(id -u)" != 0 ]; then
kdialog --title "Permission Denied! " --error "This OS optimization script need root privileges to run. "
[ ! -d '/Applications/SGOffice.app' ] && kdialog --title "Error! " --error "Sogwang Office is required to display the root tutorial! Ignore this if you already know what to do. "
cp -f /media/RedStarOS_3.5/RootTutorial.rtf ~/RootTutorial.rtf
rootsetting
/Applications/SGOffice.app/Contents/RedStar/soffice ~/RootTutorial.rtf
fi
if [ "$(id -u)" == 0 ]; then
kdialog --title "Root permission grant success! " --error "OS Optimization Process Will Now Begin. "
cp '/media/RedStarOS_3.5/RedStar/optimize.sh' '/root/Desktop/Redstar Optimize.sh' -fd
chmod +x '/root/Desktop/Redstar Optimize.sh'
konsole -e bash -c '/root/Desktop/Redstar\ Optimize.sh'
rm -f '/root/Desktop/Redstar Optimize.sh'
fi
